name: Build Kernel (KSUN + SusFS)

on:
  push:
    branches: [ "ksu-susfs" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ksu-susfs
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git bc bison flex libssl-dev make zip \
        gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi device-tree-compiler \
        libncurses5-dev ccache

    - name: Download Clang Toolchain (ZyC-Clang)
      run: |
        git clone --depth=1 https://gitlab.com/Panchajanya1999/azure-clang.git clang
        export PATH=$PWD/clang/bin:$PATH

    - name: Set Kernel Name & Build
      run: |
        export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
        export CC=clang

        cd kernel-5.10

        echo "CONFIG_TRIM_UNUSED_KSYMS=n" >> arch/arm64/configs/a24_defconfig
        echo "CONFIG_TRIM_UNUSED_KSYMS=n" >> arch/arm64/configs/a24_00_defconfig

        echo 'CONFIG_LOCALVERSION="-OLI88-KSUN"' >> arch/arm64/configs/a24_defconfig
        echo 'CONFIG_LOCALVERSION="-OLI88-KSUN"' >> arch/arm64/configs/a24_00_defconfig
        
        # Derlemeyi Ba≈ülat
        make a24_defconfig
        make -j$(nproc) Image.gz-dtb dtbo.img

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: Image-KSU-SusFS
        path: |
          kernel-5.10/arch/arm64/boot/Image.gz-dtb
          kernel-5.10/arch/arm64/boot/dtbo.img
          kernel-5.10/arch/arm64/boot/*.dtb
